@startuml
class Animal {
    # nombre: String
    # edad: int
    + comer(): void
    + dormir(): void
}

class Perro extends Animal {
    + ladrar(): void
}

class Gato extends Animal {
    + maullar(): void
}
@enduml